export const GET_TEMPLATE = 'GET_TEMPLATE'
export const GET_TEMPLATE_SUCCEEDED = 'GET_TEMPLATE_SUCCEEDED'
export const GET_TEMPLATE_FAILED = 'GET_TEMPLATE_FAILED'

export const ADD_TEMPLATE = 'ADD_TEMPLATE'
export const ADD_TEMPLATE_SUCCEEDED = 'ADD_TEMPLATE_SUCCEEDED'
export const ADD_TEMPLATE_FAILED = 'ADD_TEMPLATE_FAILED'

export const MOD_TEMPLATE = 'MOD_TEMPLATE'
export const MOD_TEMPLATE_SUCCEEDED = 'MOD_TEMPLATE_SUCCEEDED'
export const MOD_TEMPLATE_FAILED = 'MOD_TEMPLATE_FAILED'

export const DEL_TEMPLATE = 'DEL_TEMPLATE'
export const DEL_TEMPLATE_SUCCEEDED = 'DEL_TEMPLATE_SUCCEEDED'
export const DEL_TEMPLATE_FAILED = 'DEL_TEMPLATE_FAILED'

export const UPDATE_SSR_TEMPLATE = 'UPDATE_SSR_TEMPLATE'

export const SEARCH_TEMPLATE = 'SEARCH_TEMPLATE'
export const SEARCH_TEMPLATE_SUCCEEDED = 'SEARCH_TEMPLATE_SUCCEEDED'
export const SEARCH_TEMPLATE_FAILED = 'SEARCH_TEMPLATE_FAILED'

export const BATCH_DEL_TEMPLATE = 'BATCH_DEL_TEMPLATE'
export const BATCH_DEL_TEMPLATE_SUCCEEDED = 'BATCH_DEL_TEMPLATE_SUCCEEDED'
export const BATCH_DEL_TEMPLATE_FAILED = 'BATCH_DEL_TEMPLATE_FAILED'
