declare const sourceFolder: string;
declare const destFolder: string;
declare const isLocal: boolean;
declare const mysqlUser: any, mysqlPassword: any, mysqlHost: any, mysqlPort: any, mysqlDatabase: any;
declare const generationPath = "../generation";
declare const clientPathSource = "../client";
declare const clientPath = "./client";
declare const serverPathSource = "../server";
declare const serverPath = "./server";
declare const pagesPathSource = "../pages";
declare const pagesPath = "./pages";
declare const publicPathSource = "../public";
declare const publicPath = "./public";
declare const scriptsPathSource = "../scripts";
declare const scriptsPath = "./scripts";
declare const typesPathSource = "../types";
declare const typesPath = "./types";
declare const reduxPath = "/redux";
declare const servicePath = "/service";
declare const styledPath = "/styled";
declare const styledLayoutPath = "/layout";
declare const utilsPath = "/utils";
declare const layoutPath = "/layout";
declare const componentsPath = "/components";
declare const modulesPath = "/modules";
declare const apisPath = "/apis";
declare const sqlPath = "/sql";
declare const utilsMenuPath = "/menu.tsx";
declare const reduxReducersPath = "/reducers.ts";
declare const slbHealthCheckPath = "/slbhealthcheck.html";
declare const packagePath = "/package.json";
declare const restPath = "/rest.js";
declare const sourceGenerationPath: string;
declare const sourceClientPath: string;
declare const sourceClientPathGeneration: string;
declare const sourceServerPath: string;
declare const sourceServerPathGeneration: string;
declare const sourcePagesPath: string;
declare const sourcePublicPath: string;
declare const sourceScriptsPath: string;
declare const sourceTypesPath: string;
declare const projectClientPath: string;
declare const projectPublicPath: string;
declare const destClientPath: string;
declare const destClientReduxPath: string;
declare const destClientServicePath: string;
declare const destClientStyledPath: string;
declare const destClientStyledLayoutPath: string;
declare const destClientUtilsPath: string;
declare const destClientLayoutPath: string;
declare const destServerPath: string;
declare const destServerModulesPath: string;
declare const destServerApisPath: string;
declare const destServerSqlPath: string;
declare const destServerUtilsPath: string;
declare const destPagesPath: string;
declare const destPublicPath: string;
declare const destScriptsPath: string;
declare const destTypesPath: string;
declare const destClientUtilsMenuPath: string;
declare const destClientReduxReducersAllPath: string;
declare const destPublicHealthCheckPath: string;
declare const destPackagePath: string;
declare const destServerRestPath: string;
export { sourceFolder, destFolder, isLocal, generationPath, clientPathSource, clientPath, serverPathSource, serverPath, pagesPathSource, pagesPath, publicPathSource, publicPath, scriptsPathSource, scriptsPath, typesPathSource, typesPath, reduxPath, servicePath, styledPath, styledLayoutPath, utilsPath, layoutPath, componentsPath, modulesPath, apisPath, sqlPath, utilsMenuPath, reduxReducersPath, slbHealthCheckPath, packagePath, restPath, sourceGenerationPath, sourceClientPath, sourceClientPathGeneration, sourceServerPath, sourceServerPathGeneration, sourcePagesPath, sourcePublicPath, sourceScriptsPath, sourceTypesPath, projectClientPath, projectPublicPath, destClientPath, destClientReduxPath, destClientServicePath, destClientStyledPath, destClientStyledLayoutPath, destClientUtilsPath, destClientLayoutPath, destServerPath, destServerModulesPath, destServerApisPath, destServerSqlPath, destServerUtilsPath, destPagesPath, destPublicPath, destScriptsPath, destTypesPath, destClientUtilsMenuPath, destClientReduxReducersAllPath, destPublicHealthCheckPath, destPackagePath, destServerRestPath, mysqlUser, mysqlPassword, mysqlHost, mysqlPort, mysqlDatabase, };
